### ISSUE TITLE
Getting "Could Not Connect to Repository" Error

### ISSUE THREAD

**Issue by janwil123** [yllar/yllar.github.io#1]
I am trying to install Jupiter and ERR plugins on Kodi 20, and I have tried both XBian on Raspberry Pi 3 and Kodi on Manjaro Linux.  I can get the .zip file and see Yllar's XBMC Addons in the menu, but once I click there, I get "Could Not Connect to Repository". What could possibly be the issue here?

**Comment by yllar** [comment]
Please update repository manually to 1.0.1 (as 20 broke automatic updates due to structure change) https://yllar.github.io/kodi/
